<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <link name="base_link"/>   <!--base_footprint -->

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <xacro:property name="base_mass"        value="1.0"/>
    <xacro:property name="base_length"      value="0.23"/>
    <xacro:property name="base_height"      value="0.048"/>
    <xacro:property name="base_width"       value="0.16"/>

    <xacro:property name="wheel_mass"       value="0.06"/>
    <xacro:property name="wheel_radius"     value="0.0425"/>
    <xacro:property name="wheel_thickness"  value="0.04"/>


    <link name="chassis">

        <visual name="">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/> <!-- 0.23 0.16 0.048 -->
            </geometry>
            <material name="">
                <color rgba="1.0 1.0 0.0 1.0"/>
                <texture filename=""/>
            </material>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/> <!-- 0.23 0.16 0.048 -->
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="${base_length}" y="${base_width}" z="${base_height}">
            <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>

    </link>

    <gazebo reference = "chassis">
        <material>Gazebo/Yellow</material> 
    </gazebo>

    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chassis"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>



    <!-- All Wheel links and joints -->


    <xacro:macro name="wheel" params="name x y">

        <link name="wheel_${name}_link">

            <visual name="">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="0.04"/>
                </geometry>
                <material name="black">
                    <color rgba=".0 .0 0.0 1.0"/>
                </material>
            </visual>

            <collision>
                    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                    <geometry>
                        <sphere radius="${wheel_radius}"/>
                    </geometry>
            </collision>

            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference = "wheel_${name}_link">
            <material>Gazebo/Black</material> 
        </gazebo>

        <joint name="wheel_${name}_joint" type="continuous">
            <parent link="chassis"/>
            <child link="wheel_${name}_link"/>
            <origin xyz="${x} ${y} -0.007" rpy="-1.57 0.0 0.0"/>
            <axis xyz=".0 .0 1.0"/>
            <!-- <limit effort="10000" velocity="1000" /> -->
	        <!-- <dynamics damping="1.0" friction="1.0" /> -->
        </joint>

    </xacro:macro>

    <xacro:wheel name="front_left"  x="0.085" y =" 0.105"/>
    <xacro:wheel name="rear_left" x="-0.085" y =" 0.105"/>
    <xacro:wheel name="rear_right"  x="-0.085" y =" -0.105"/>
    <xacro:wheel name="front_right"   x="0.085" y =" -0.105"/>

</robot>