amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "omnidirectional"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False


controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 5.0
    controller_plugin_types: ["dwb_core::DWBLocalPlanner"]
    controller_plugin_ids: ["FollowPath"]
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01

    # DWB parameters
    FollowPath.debug_trajectory_details: True
    movement_time_allowance: 20.0
    required_movement_radius: 0.2
    FollowPath.min_vel_x: -0.5
    FollowPath.min_vel_y: -0.5
    FollowPath.max_vel_x: 0.5
    FollowPath.max_vel_y: 0.5
    FollowPath.max_vel_theta: 0.5
    FollowPath.min_speed_xy: -0.3
    FollowPath.max_speed_xy: 0.5
    FollowPath.min_speed_theta: -0.5
    FollowPath.min_x_velocity_threshold: 0.01
    # Add high threshold velocity for turtlebot 3 issue.
    # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
    FollowPath.min_y_velocity_threshold: 0.01
    FollowPath.min_theta_velocity_threshold: 0.01
    FollowPath.acc_lim_x: 1.0
    FollowPath.acc_lim_y: 1.0
    FollowPath.acc_lim_theta: 1.0
    FollowPath.decel_lim_x: -1.0
    FollowPath.decel_lim_y: -1.0
    FollowPath.decel_lim_theta: -1.0
    FollowPath.vx_samples: 20
    FollowPath.vy_samples: 20
    FollowPath.vtheta_samples: 10
    FollowPath.sim_time: 5.0
    FollowPath.linear_granularity: 0.6
    FollowPath.angular_granularity: 0.3
    FollowPath.time_granularity: 0.05
    FollowPath.xy_goal_tolerance: 0.2
    FollowPath.yaw_goal_tolerance: 0.4
    FollowPath.transform_tolerance: 0.2
    FollowPath.critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "Twirling"]
    FollowPath.ObstacleFootprint.scale: 10.0
    FollowPath.PathAlign.scale: 0.0
    FollowPath.GoalAlign.scale: 32.0
    FollowPath.Oscillation.scale: 0.0
    FollowPath.PathDist.scale: 32.0
    FollowPath.GoalDist.scale: 24.0
    FollowPath.RotateToGoal.scale: 32.0
    FollowPath.BaseObstacle.scale: 10.0
    FollowPath.Twirling.scale: 40.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      robot_base_frame: base_link
      use_sim_time: False
      global_frame: odom
      plugin_names: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::VoxelLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.05
      robot_radius: 0.626
      inflation_layer:
        cost_scaling_factor: 1.0
        inflation_radius: 1.2
      obstacle_layer:
        enabled: True
        observation_sources: scan_1 scan_2
        scan_1:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        scan_2:
          topic: /scan_2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 10
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: points2
        points2:
          topic: /points2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      robot_base_frame: base_link
      global_frame: map
      use_sim_time: False
      plugin_names: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::VoxelLayer", "nav2_costmap_2d::InflationLayer"]
      robot_radius: 0.626
      resolution: 0.05
      obstacle_layer:
        enabled: True
        observation_sources: scan_1 scan_2
        scan_1:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        scan_2:
          topic: /scan_2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 10
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: points2
        points2:
          topic: /points2
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "turtlebot3_world.yaml"

planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: False
    GridBased.tolerance: 1.0
    GridBased.use_astar: false
    GridBased.allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    cycle_frequency: 10.0
    footprint_topic: local_costmap/published_footprint
    max_rotational_vel: 0.1
    min_rotational_vel: 0.05
    plugin_names:
    - Spin
    - BackUp
    - Wait
    plugin_types:
    - nav2_recoveries/Spin
    - nav2_recoveries/BackUp
    - nav2_recoveries/Wait
    rotational_acc_lim: 0.2
    simulate_ahead_time: 2.0
    use_sim_time: False